"""
Small Logitech device catalog entries.

These records are maintained device by device after the Mouser UI has been
checked locally. We keep the catalog small so supported devices stay easy to
review and maintain.
"""

from __future__ import annotations


MX_ANYWHERE_BUTTONS = (
    "middle",
    "gesture",
    "gesture_left",
    "gesture_right",
    "gesture_up",
    "gesture_down",
    "xbutton1",
    "xbutton2",
    "hscroll_left",
    "hscroll_right",
)

MX_ANYWHERE_SMARTSHIFT_BUTTONS = (
    *MX_ANYWHERE_BUTTONS,
    "mode_shift",
)


def _hotspot(
    button_key: str,
    label: str,
    summary_type: str,
    norm_x: float,
    norm_y: float,
    *,
    label_side: str,
    label_off_x: int,
    label_off_y: int,
    is_hscroll: bool = False,
) -> dict[str, object]:
    return {
        "buttonKey": button_key,
        "label": label,
        "summaryType": summary_type,
        "normX": norm_x,
        "normY": norm_y,
        "labelSide": label_side,
        "labelOffX": label_off_x,
        "labelOffY": label_off_y,
        "isHScroll": is_hscroll,
    }


def _layout(
    key: str,
    label: str,
    image_asset: str,
    image_width: int,
    image_height: int,
    hotspots: list[dict[str, object]],
) -> dict[str, object]:
    return {
        "key": key,
        "label": label,
        "image_asset": image_asset,
        "image_width": image_width,
        "image_height": image_height,
        "interactive": True,
        "manual_selectable": False,
        "note": "",
        "hotspots": hotspots,
    }


LOGI_DEVICE_SPECS = (
    {
        "key": "mx_master_4",
        "display_name": "MX Master 4",
        "product_ids": (0xB042, 0xB048),
        "aliases": (
            "Logitech MX Master 4",
            "Wireless Mouse MX Master 4",
            "MX Master 4 for Mac",
            "MX Master 4 for Business",
            "MX_Master_4",
        ),
        "ui_layout": "mx_master_4",
        "image_asset": "logitech-mice/mx_master_4/mouse.png",
    },
    {
        "key": "mx_master_3s",
        "display_name": "MX Master 3S",
        "product_ids": (0xB034, 0xB043),
        "aliases": (
            "Logitech MX Master 3S",
            "MX Master 3S for Mac",
            "MX Master 3S for Business",
        ),
        "ui_layout": "mx_master_3s",
        "image_asset": "logitech-mice/mx_master_3s/mouse.png",
    },
    {
        "key": "mx_master_3",
        "display_name": "MX Master 3",
        "product_ids": (0xB023, 0xB028),
        "aliases": (
            "Wireless Mouse MX Master 3",
            "MX Master 3 for Mac",
            "MX Master 3 Mac",
            "MX Master 3 for Business",
        ),
        "ui_layout": "mx_master_3",
        "image_asset": "logitech-mice/mx_master_3/mouse.png",
    },
    {
        "key": "mx_master_2s",
        "display_name": "MX Master 2S",
        "product_ids": (0xB019,),
        "aliases": (
            "Wireless Mouse MX Master 2S",
            "MX Master 2S",
        ),
        "ui_layout": "mx_master_2s",
        "image_asset": "logitech-mice/mx_master_2s/mouse.png",
        "dpi_max": 4000,
    },
    {
        "key": "mx_master",
        "display_name": "MX Master",
        "product_ids": (0xB012,),
        "aliases": (
            "Wireless Mouse MX Master",
            "MX Master",
        ),
        "ui_layout": "mx_master_classic",
        "image_asset": "logitech-mice/mx_master/mouse.png",
        "dpi_max": 4000,
    },
    {
        "key": "mx_anywhere_3s",
        "display_name": "MX Anywhere 3S",
        "product_ids": (0xB037,),
        "aliases": (
            "Logitech MX Anywhere 3S",
            "MX Anywhere 3S for Mac",
        ),
        "ui_layout": "mx_anywhere_3s",
        "image_asset": "logitech-mice/mx_anywhere_3s/mouse.png",
        "supported_buttons": MX_ANYWHERE_SMARTSHIFT_BUTTONS,
        "dpi_max": 8000,
    },
    {
        "key": "mx_anywhere_3",
        "display_name": "MX Anywhere 3",
        "product_ids": (0xB025, 0xB02D),
        "aliases": (
            "MX Anywhere 3 for Mac",
            "MX Anywhere 3 for Business",
        ),
        "ui_layout": "mx_anywhere_3",
        "image_asset": "logitech-mice/mx_anywhere_3/mouse.png",
        "supported_buttons": MX_ANYWHERE_SMARTSHIFT_BUTTONS,
        "dpi_max": 4000,
    },
    {
        "key": "mx_anywhere_2s",
        "display_name": "MX Anywhere 2S",
        "product_ids": (0xB01A,),
        "aliases": (
            "Wireless Mobile Mouse MX Anywhere 2S",
            "MX Anywhere 2S",
        ),
        "ui_layout": "mx_anywhere_2s",
        "image_asset": "logitech-mice/mx_anywhere_2s/mouse.png",
        "supported_buttons": MX_ANYWHERE_BUTTONS,
        "dpi_max": 4000,
    },
    # G502 X family (Lightspeed wireless via c547/409f, wired c098).
    # Uses onboard profiles for most G-buttons; OS-visible side buttons,
    # wheel tilt (hscroll), middle click, and DPI are exposed. No
    # REPROG_CONTROLS_V4 advertised in standard feature set, so extra
    # buttons rely on evdev/keyboard events or onboard config.
    {
        "key": "g502_x_lightspeed",
        "display_name": "G502 X Lightspeed",
        "product_ids": (0xC547, 0x409F, 0xC098),
        "aliases": (
            "G502 X LIGHTSPEED",
            "G502 X LS",
            "Logitech G502 X LS",
            "G502 X Plus",
            "G502 X",
            "G502X",
            "G502 X Wired",
        ),
        "ui_layout": "generic_mouse",
        "image_asset": "icons/mouse-simple.svg",
        "supported_buttons": (
            "middle",
            "xbutton1",
            "xbutton2",
            "hscroll_left",
            "hscroll_right",
        ),
        "dpi_min": 100,
        "dpi_max": 25600,
    },
)


LOGI_DEVICE_LAYOUTS = {
    "mx_master_4": _layout(
        "mx_master_4",
        "MX Master 4",
        "logitech-mice/mx_master_4/mouse.png",
        256,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.755,
                0.19,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.473,
                0.60,
                label_side="right",
                label_off_x=160,
                label_off_y=20,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.425,
                0.47,
                label_side="right",
                label_off_x=160,
                label_off_y=-90,
            ),
            _hotspot(
                "gesture",
                "Gesture button",
                "gesture",
                0.386,
                0.361,
                label_side="left",
                label_off_x=-260,
                label_off_y=20,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll left",
                "hscroll",
                0.565,
                0.564,
                label_side="right",
                label_off_x=160,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.805,
                0.395,
                label_side="right",
                label_off_x=160,
                label_off_y=60,
            ),
        ],
    ),
    "mx_master_3s": _layout(
        "mx_master_3s",
        "MX Master 3S",
        "logitech-mice/mx_master_3s/mouse.png",
        248,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.71,
                0.15,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.45,
                0.60,
                label_side="right",
                label_off_x=160,
                label_off_y=20,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.35,
                0.43,
                label_side="left",
                label_off_x=-260,
                label_off_y=-10,
            ),
            _hotspot(
                "gesture",
                "Gesture button",
                "gesture",
                0.08,
                0.58,
                label_side="left",
                label_off_x=-260,
                label_off_y=40,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll left",
                "hscroll",
                0.55,
                0.515,
                label_side="right",
                label_off_x=160,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.81,
                0.34,
                label_side="right",
                label_off_x=160,
                label_off_y=60,
            ),
        ],
    ),
    "mx_master_3": _layout(
        "mx_master_3",
        "MX Master 3",
        "logitech-mice/mx_master_3/mouse.png",
        248,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.71,
                0.15,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.45,
                0.60,
                label_side="right",
                label_off_x=160,
                label_off_y=20,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.35,
                0.43,
                label_side="left",
                label_off_x=-260,
                label_off_y=-10,
            ),
            _hotspot(
                "gesture",
                "Gesture button",
                "gesture",
                0.08,
                0.58,
                label_side="left",
                label_off_x=-260,
                label_off_y=40,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll left",
                "hscroll",
                0.55,
                0.515,
                label_side="right",
                label_off_x=160,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.81,
                0.34,
                label_side="right",
                label_off_x=160,
                label_off_y=60,
            ),
        ],
    ),
    "mx_master_2s": _layout(
        "mx_master_2s",
        "MX Master 2S",
        "logitech-mice/mx_master_2s/mouse.png",
        261,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.73,
                0.18,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.49,
                0.70,
                label_side="right",
                label_off_x=160,
                label_off_y=20,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.47,
                0.58,
                label_side="right",
                label_off_x=160,
                label_off_y=-30,
            ),
            _hotspot(
                "gesture",
                "Gesture button",
                "gesture",
                0.13,
                0.69,
                label_side="left",
                label_off_x=-260,
                label_off_y=40,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll left",
                "hscroll",
                0.40,
                0.46,
                label_side="left",
                label_off_x=-240,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.79,
                0.36,
                label_side="right",
                label_off_x=160,
                label_off_y=0,
            ),
        ],
    ),
    "mx_master_classic": _layout(
        "mx_master_classic",
        "MX Master",
        "logitech-mice/mx_master/mouse.png",
        262,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.73,
                0.18,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.49,
                0.70,
                label_side="right",
                label_off_x=160,
                label_off_y=20,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.47,
                0.58,
                label_side="right",
                label_off_x=160,
                label_off_y=-30,
            ),
            _hotspot(
                "gesture",
                "Gesture button",
                "gesture",
                0.13,
                0.69,
                label_side="left",
                label_off_x=-260,
                label_off_y=40,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll left",
                "hscroll",
                0.40,
                0.46,
                label_side="left",
                label_off_x=-240,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.79,
                0.36,
                label_side="right",
                label_off_x=160,
                label_off_y=0,
            ),
        ],
    ),
    "mx_anywhere_2s": _layout(
        "mx_anywhere_2s",
        "MX Anywhere 2S",
        "logitech-mice/mx_anywhere_2s/mouse.png",
        253,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.52,
                0.385,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.02,
                0.58,
                label_side="left",
                label_off_x=-240,
                label_off_y=10,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.02,
                0.44,
                label_side="left",
                label_off_x=-260,
                label_off_y=-10,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll",
                "hscroll",
                0.38,
                0.195,
                label_side="left",
                label_off_x=-240,
                label_off_y=-70,
                is_hscroll=True,
            ),
        ],
    ),
    "mx_anywhere_3": _layout(
        "mx_anywhere_3",
        "MX Anywhere 3",
        "logitech-mice/mx_anywhere_3/mouse.png",
        239,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.72,
                0.17,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.28,
                0.61,
                label_side="left",
                label_off_x=-240,
                label_off_y=10,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.22,
                0.43,
                label_side="left",
                label_off_x=-260,
                label_off_y=-10,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll",
                "hscroll",
                0.70,
                0.19,
                label_side="right",
                label_off_x=160,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.75,
                0.34,
                label_side="right",
                label_off_x=160,
                label_off_y=0,
            ),
        ],
    ),
    "mx_anywhere_3s": _layout(
        "mx_anywhere_3s",
        "MX Anywhere 3S",
        "logitech-mice/mx_anywhere_3s/mouse.png",
        239,
        400,
        [
            _hotspot(
                "middle",
                "Middle button",
                "mapping",
                0.71,
                0.16,
                label_side="right",
                label_off_x=120,
                label_off_y=-120,
            ),
            _hotspot(
                "xbutton1",
                "Back button",
                "mapping",
                0.28,
                0.60,
                label_side="left",
                label_off_x=-240,
                label_off_y=10,
            ),
            _hotspot(
                "xbutton2",
                "Forward button",
                "mapping",
                0.22,
                0.41,
                label_side="left",
                label_off_x=-260,
                label_off_y=-10,
            ),
            _hotspot(
                "hscroll_left",
                "Horizontal scroll",
                "hscroll",
                0.37,
                0.24,
                label_side="left",
                label_off_x=-240,
                label_off_y=-70,
                is_hscroll=True,
            ),
            _hotspot(
                "mode_shift",
                "Mode shift button",
                "mapping",
                0.75,
                0.34,
                label_side="right",
                label_off_x=160,
                label_off_y=0,
            ),
        ],
    ),
}
